package white.noise.sounds.baby.sleep.utils

object Constants {
    const val ACTION_START_TIMER = "ACTION_START_TIMER"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_PLAY_OR_PAUSE_ALL_SOUNDS = "ACTION_PLAY_OR_PAUSE_ALL_SOUNDS"
    const val ACTION_PLAY_OR_STOP_SOUND = "ACTION_PLAY_OR_STOP_SOUND"
    const val ACTION_PLAY_SOUND = "ACTION_PLAY_SOUND"
    const val ACTION_STOP_SOUND = "ACTION_STOP_SOUND"
    const val ACTION_STOP_ALL_SOUNDS = "ACTION_STOP_ALL_SOUNDS"
    const val ACTION_CHANGE_VOLUME = "ACTION_CHANGE_VOLUME"

    const val LAUNCHER = "LAUNCHER"
    const val SOUNDS_LAUNCHER = "SOUNDS_LAUNCHER"
    const val MIX_LAUNCHER = "MIX_LAUNCHER"
    const val PLAYER_LAUNCHER = "PLAYER_LAUNCHER"

    const val EXTRA_TIME = "EXTRA_TIME"
    const val EXTRA_SOUND = "EXTRA_SOUND"
    const val EXTRA_MIX = "EXTRA_MIX"

    const val NOTIFICATION_CHANNEL_ID = "timer_channel"
    const val NOTIFICATION_CHANNEL_NAME = "timer"
    const val NOTIFICATION_ID = 1

}